/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import com.qoppa.pdfWriter.PDFPrinterJob;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JPanel;

/**
 *
 * @author jpcv2
 */
public class Factura extends javax.swing.JFrame implements Printable {

    /**
     * Creates new form Factura
     */
    public Factura() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabelTitleModal = new javax.swing.JLabel();
        jLabelNameCliente = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabelCambio = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabelNameVendedor = new javax.swing.JLabel();
        jLabelTicketsAcum = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabelTicketsComprados = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabelEfectivo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel32 = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        btPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel.setBackground(new java.awt.Color(255, 255, 255));
        jPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 51), 3));
        jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(205, 31, 50));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exit2.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exit.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 60, 50));

        jLabelTitleModal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTitleModal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitleModal.setText("Factura de venta");
        jPanel2.add(jLabelTitleModal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 220, -1));

        jPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 50));

        jLabelNameCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNameCliente.setText("Value");
        jPanel.add(jLabelNameCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 400, 40));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel25.setText("Fecha realizado");
        jPanel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 180, 39));

        jLabelCambio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCambio.setText("Value");
        jPanel.add(jLabelCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 400, 40));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel26.setText("Cliente");
        jPanel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 39));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel27.setText("Vendedor");
        jPanel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 110, 39));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel28.setText("Tickets acumulados");
        jPanel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 190, 39));

        jLabelNameVendedor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNameVendedor.setText("Value");
        jPanel.add(jLabelNameVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 400, 40));

        jLabelTicketsAcum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTicketsAcum.setText("Value");
        jPanel.add(jLabelTicketsAcum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 180, 40));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel29.setText("Tickets comprados ");
        jPanel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 180, 39));

        jLabelTicketsComprados.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTicketsComprados.setText("Value");
        jPanel.add(jLabelTicketsComprados, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 170, 40));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel30.setText("Total");
        jPanel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 180, 39));

        jLabelTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTotal.setText("Value");
        jPanel.add(jLabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 400, 40));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel31.setText("Efectivo");
        jPanel.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 180, 39));

        jLabelEfectivo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelEfectivo.setText("Value");
        jPanel.add(jLabelEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 400, 40));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/univalle.jpg"))); // NOI18N
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 610, -1, 50));
        jPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));
        jPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 180, 0));
        jPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 180, 10));
        jPanel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 170, 20));
        jPanel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 400, 10));
        jPanel.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 400, 10));
        jPanel.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 400, 20));
        jPanel.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 400, 20));
        jPanel.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 400, 20));
        jPanel.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 400, 20));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel32.setText("Cambio");
        jPanel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 180, 39));

        jLabelFecha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelFecha.setText("Value");
        jPanel.add(jLabelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 400, 40));

        btPrint.setText("Print");
        btPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrintActionPerformed(evt);
            }
        });
        jPanel.add(btPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 630, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrintActionPerformed
        // TODO add your handling code here:
        printSale();
    }//GEN-LAST:event_btPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPrint;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabelCambio;
    public javax.swing.JLabel jLabelEfectivo;
    public javax.swing.JLabel jLabelFecha;
    public javax.swing.JLabel jLabelNameCliente;
    public javax.swing.JLabel jLabelNameVendedor;
    public javax.swing.JLabel jLabelTicketsAcum;
    public javax.swing.JLabel jLabelTicketsComprados;
    public javax.swing.JLabel jLabelTitleModal;
    public javax.swing.JLabel jLabelTotal;
    public javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables

    public void printSale() {
        try {
            // create a PDF Printer Job
            PDFPrinterJob printer = (PDFPrinterJob) PDFPrinterJob.getPrinterJob();
            // set the printable object 
            printer.setPrintable(this);
            // set number of copies to 1 
            printer.setCopies(1);
            // print and save the document
            Date d1 = new Date();
            SimpleDateFormat df = new SimpleDateFormat("MMddYYYYHHmma");
            String formattedDate = df.format(d1);
            printer.print(".\\src\\files\\facturas\\factura" +formattedDate+ ".pdf");
            // output done message 
            System.out.println("Done!");
        } catch (Throwable t) {
            t.printStackTrace();
        }
    }

    @Override
    public int print(Graphics g, PageFormat pf, int pageIndex) {
        try {
            if (pageIndex == 0) {

                // translate the graphics for margins
                g.translate(100, 100);

                // print the panel to the graphics on page 0
                btPrint.setVisible(false);
                jPanel.print(g);
                btPrint.setVisible(true);
                return Printable.PAGE_EXISTS;
            } else {
                return Printable.NO_SUCH_PAGE;
            }
        } catch (Exception e) {
            return Printable.NO_SUCH_PAGE;
        }
    }
}
