/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import managers.ControladorGestionPermisos;

/**
 *
 * @author jpcv2
 */
public class GestionPermisos extends javax.swing.JFrame {

    /**
     * Creates new form ErrorMessage
     */
    Color red_error;
    public ControladorGestionPermisos manager;

    public GestionPermisos() {
        initComponents();
        manager = new ControladorGestionPermisos(this);

        red_error = new Color(205, 31, 50);

        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabelTitleModal = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jPanelAceptar = new javax.swing.JPanel();
        jLabelAceptar1 = new javax.swing.JLabel();
        jLabelAceptar2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jPanelActions = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabelConstructModule = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanelAddKeys = new javax.swing.JPanel();
        jLabelAceptar = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldModuloNuevo = new javax.swing.JTextField();
        jPanelAddKeys1 = new javax.swing.JPanel();
        jLabelAceptar3 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldPermisoNuevo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabelUserNamePerm1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxModulos = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(205, 31, 50));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exit2.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exit.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 60, 50));

        jLabelTitleModal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTitleModal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitleModal.setText("Gestión de permisos por usuario,");
        jPanel2.add(jLabelTitleModal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 370, -1));

        jLabelUserName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelUserName.setForeground(new java.awt.Color(204, 204, 204));
        jLabelUserName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelUserName.setText("Username");
        jPanel2.add(jLabelUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 270, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 880, 50));

        jPanelAceptar.setBackground(new java.awt.Color(255, 255, 255));
        jPanelAceptar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(205, 31, 50), 2, true));
        jPanelAceptar.setEnabled(false);
        jPanelAceptar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanelAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAceptarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAceptarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAceptarMouseExited(evt);
            }
        });
        jPanelAceptar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAceptar1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelAceptar1.setForeground(new java.awt.Color(205, 31, 50));
        jLabelAceptar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAceptar1.setText("Asignar permisos");
        jPanelAceptar.add(jLabelAceptar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 6, 200, 40));

        jPanel1.add(jPanelAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 570, 210, 50));

        jLabelAceptar2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelAceptar2.setForeground(new java.awt.Color(205, 31, 50));
        jLabelAceptar2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelAceptar2.setText("Asignar permisos a: ");
        jPanel1.add(jLabelAceptar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 240, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 850, 10));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Acciones del módulo seleccionado");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 390, 20));

        jPanelActions.setBackground(new java.awt.Color(255, 255, 255));
        jPanelActions.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jPanelActions, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 390, 420));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelConstructModule.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelConstructModule.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelConstructModule.setText("Añade un permisos y módulos...");
        jPanel3.add(jLabelConstructModule, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 380, 10));

        jPanelAddKeys.setBackground(new java.awt.Color(255, 255, 255));
        jPanelAddKeys.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(205, 31, 50), 2));
        jPanelAddKeys.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAddKeysMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAddKeysMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAddKeysMouseExited(evt);
            }
        });

        jLabelAceptar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelAceptar.setForeground(new java.awt.Color(205, 31, 50));
        jLabelAceptar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAceptar.setText("Agregar permiso");
        jPanelAddKeys.add(jLabelAceptar);

        jPanel3.add(jPanelAddKeys, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 390, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Permiso");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 390, 20));

        jTextFieldModuloNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldModuloNuevoActionPerformed(evt);
            }
        });
        jPanel3.add(jTextFieldModuloNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 390, 30));

        jPanelAddKeys1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelAddKeys1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(205, 31, 50), 2));
        jPanelAddKeys1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAddKeys1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAddKeys1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAddKeys1MouseExited(evt);
            }
        });

        jLabelAceptar3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelAceptar3.setForeground(new java.awt.Color(205, 31, 50));
        jLabelAceptar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAceptar3.setText("Agregar módulo");
        jPanelAddKeys1.add(jLabelAceptar3);

        jPanel3.add(jPanelAddKeys1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 390, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Módulo");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 390, 20));

        jTextFieldPermisoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPermisoNuevoActionPerformed(evt);
            }
        });
        jPanel3.add(jTextFieldPermisoNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 390, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 410, 320));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("3. Presione 'Asignar permisos' para agregar los permisos.");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, 400, 40));

        jLabelUserNamePerm1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelUserNamePerm1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelUserNamePerm1.setText("Nombre usuario");
        jPanel1.add(jLabelUserNamePerm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 600, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Agregue permisos al usuario en cada módulo de manera independiente...");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 520, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("1. Seleccione un módulo o funcionalidad.");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, 390, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("2. Seleccione los permisos a asignar de ese módulo.");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, 390, 40));

        jComboBoxModulos.setBorder(null);
        jComboBoxModulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBoxModulosMousePressed(evt);
            }
        });
        jPanel1.add(jComboBoxModulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 390, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Módulo");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 390, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanelAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAceptarMouseClicked
        // TODO add your handling code here:
        manager.asignUserPermissions();
    }//GEN-LAST:event_jPanelAceptarMouseClicked

    private void jPanelAceptarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAceptarMouseEntered
        // TODO add your handling code here:
        jPanelAceptar.setBackground(red_error);
        jLabelAceptar.setForeground(Color.white);
    }//GEN-LAST:event_jPanelAceptarMouseEntered

    private void jPanelAceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAceptarMouseExited
        // TODO add your handling code here:
        jPanelAceptar.setBackground(Color.white);
        jLabelAceptar.setForeground(red_error);
    }//GEN-LAST:event_jPanelAceptarMouseExited

    private void jComboBoxModulosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxModulosMousePressed
        // TODO add your handling code here:
        manager.createKeysModule();
    }//GEN-LAST:event_jComboBoxModulosMousePressed

    private void jPanelAddKeysMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAddKeysMouseEntered
        // TODO add your handling code here:
        jPanelAddKeys.setBackground(red_error);
        jPanelAddKeys.setForeground(Color.white);
    }//GEN-LAST:event_jPanelAddKeysMouseEntered

    private void jPanelAddKeysMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAddKeysMouseExited
        // TODO add your handling code here:
        jPanelAddKeys.setBackground(Color.white);
        jPanelAddKeys.setForeground(red_error);
    }//GEN-LAST:event_jPanelAddKeysMouseExited

    private void jPanelAddKeysMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAddKeysMouseClicked
        // TODO add your handling code here:
        //Add key
    }//GEN-LAST:event_jPanelAddKeysMouseClicked

    private void jTextFieldModuloNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldModuloNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldModuloNuevoActionPerformed

    private void jPanelAddKeys1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAddKeys1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelAddKeys1MouseClicked

    private void jPanelAddKeys1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAddKeys1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelAddKeys1MouseEntered

    private void jPanelAddKeys1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAddKeys1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelAddKeys1MouseExited

    private void jTextFieldPermisoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPermisoNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPermisoNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public javax.swing.JComboBox<String> jComboBoxModulos;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAceptar;
    private javax.swing.JLabel jLabelAceptar1;
    private javax.swing.JLabel jLabelAceptar2;
    private javax.swing.JLabel jLabelAceptar3;
    public javax.swing.JLabel jLabelConstructModule;
    public javax.swing.JLabel jLabelTitleModal;
    public javax.swing.JLabel jLabelUserName;
    public javax.swing.JLabel jLabelUserNamePerm1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelAceptar;
    public javax.swing.JPanel jPanelActions;
    private javax.swing.JPanel jPanelAddKeys;
    private javax.swing.JPanel jPanelAddKeys1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldModuloNuevo;
    private javax.swing.JTextField jTextFieldPermisoNuevo;
    // End of variables declaration//GEN-END:variables
}
