/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author jpcv2
 */
public class SuccesMessage extends javax.swing.JFrame {

    /**
     * Creates new form ErrorMessage
     */
    
    Color green_success;
    
    public SuccesMessage() {
        green_success = new Color (0,153,102);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelTitleModal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelSubtitleModal = new javax.swing.JLabel();
        jLabelIconModal = new javax.swing.JLabel();
        jLabelBodyModal3 = new javax.swing.JLabel();
        jLabelBodyModal1 = new javax.swing.JLabel();
        jLabelBodyModal2 = new javax.swing.JLabel();
        jPanelAceptar = new javax.swing.JPanel();
        jLabelAceptar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(440, 350));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitleModal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTitleModal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitleModal.setText("Título de aviso.");
        jPanel2.add(jLabelTitleModal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 330, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exit2.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exit.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 60, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        jLabelSubtitleModal.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSubtitleModal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelSubtitleModal.setForeground(new java.awt.Color(0, 153, 51));
        jLabelSubtitleModal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSubtitleModal.setText("Subtítulo de aviso");
        jPanel1.add(jLabelSubtitleModal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 320, 40));

        jLabelIconModal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIconModal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/succes_message.png"))); // NOI18N
        jPanel1.add(jLabelIconModal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 100, 80));

        jLabelBodyModal3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelBodyModal3.setForeground(new java.awt.Color(102, 102, 102));
        jLabelBodyModal3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBodyModal3.setText("Cuerpo del aviso 3.");
        jPanel1.add(jLabelBodyModal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 400, 40));

        jLabelBodyModal1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelBodyModal1.setForeground(new java.awt.Color(102, 102, 102));
        jLabelBodyModal1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBodyModal1.setText("Cuerpo del aviso 1.");
        jPanel1.add(jLabelBodyModal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 400, 40));

        jLabelBodyModal2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelBodyModal2.setForeground(new java.awt.Color(102, 102, 102));
        jLabelBodyModal2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBodyModal2.setText("Cuerpo del aviso 2.");
        jPanel1.add(jLabelBodyModal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 400, 30));

        jPanelAceptar.setBackground(new java.awt.Color(255, 255, 255));
        jPanelAceptar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 102), 2, true));
        jPanelAceptar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanelAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAceptarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAceptarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAceptarMouseExited(evt);
            }
        });
        jPanelAceptar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAceptar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelAceptar.setForeground(new java.awt.Color(0, 153, 102));
        jLabelAceptar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAceptar.setText("Aceptar");
        jPanelAceptar.add(jLabelAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 6, 140, 40));

        jPanel1.add(jPanelAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 210, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanelAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAceptarMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jPanelAceptarMouseClicked

    private void jPanelAceptarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAceptarMouseEntered
        // TODO add your handling code here:
        jPanelAceptar.setBackground(green_success);
        jLabelAceptar.setForeground(Color.white);
    }//GEN-LAST:event_jPanelAceptarMouseEntered

    private void jPanelAceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAceptarMouseExited
        // TODO add your handling code here:
        jPanelAceptar.setBackground(Color.white);
         jLabelAceptar.setForeground(green_success);
    }//GEN-LAST:event_jPanelAceptarMouseExited
            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelAceptar;
    public javax.swing.JLabel jLabelBodyModal1;
    public javax.swing.JLabel jLabelBodyModal2;
    public javax.swing.JLabel jLabelBodyModal3;
    private javax.swing.JLabel jLabelIconModal;
    public javax.swing.JLabel jLabelSubtitleModal;
    public javax.swing.JLabel jLabelTitleModal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAceptar;
    // End of variables declaration//GEN-END:variables
}
